# Generated by Django 3.1.2 on 2020-10-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlotGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('fun_mode', models.BooleanField(default=False)),
                ('real_mode', models.BooleanField(default=True)),
                ('jackpot', models.IntegerField()),
                ('jackpot_currency', models.CharField(max_length=5)),
                ('test_field', models.CharField(default='', max_length=44)),
                ('categorys', models.ManyToManyField(to='my_app.Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('fun_mode', models.BooleanField(default=False)),
                ('real_mode', models.BooleanField(default=True)),
                ('dealer_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('test_field', models.CharField(default='', max_length=44)),
                ('dealer_language', models.CharField(max_length=20)),
                ('unlimited_seats', models.BooleanField(default=False)),
                ('categorys', models.ManyToManyField(to='my_app.Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
