# Generated by Django 3.1.2 on 2020-10-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livegame',
            old_name='categorys',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='slotgame',
            old_name='categorys',
            new_name='categories',
        ),
    ]
