# Generated by Django 3.1.2 on 2020-10-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20201021_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livegame',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='slotgame',
            name='test_field',
        ),
    ]
