# Generated by Django 3.1.2 on 2020-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201021_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegame',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slotgame',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
