# Generated by Django 3.1.2 on 2020-10-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201021_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='game_type',
            field=models.CharField(default='Live Game', max_length=20),
        ),
        migrations.AddField(
            model_name='slotgame',
            name='game_type',
            field=models.CharField(default='Slot Game', max_length=20),
        ),
    ]
